language: smalltalk

os:
  - linux

env:
  global:
    - ARTIFACT_DIR=openponk-demo-image-$TRAVIS_BUILD_NUMBER

smalltalk:
  - Pharo64-8.0
  - Pharo64-9.0

cache:
  directories:
    - $SMALLTALK_CI_BUILD_BASE/pharo-local/package-cache
